src/eighthwonder/urls.py
from django.contrib import admin
from django.urls import path, include

handler404 = 'main.views.handler404' 

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

src/main/urls.py
from django.urls import path

from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.home, name='home'),
    path('tournament/<str:tournamentName>/', views.tournamentInfo, name='tournamentInfo'),
    path('tournament/<str:tournamentName>/edit', views.tournamentEdit, name='tournamentEdit'),
    path('tournament/<str:tournamentName>/play', views.tournament, name='tournament'),
    path('error/', views.error, name='error'),
    path('createAccount/', views.accountCreation, name='accountCreation'),
    path('drinks/', views.drinks, name='drinks'),
    path('home/', views.homeRedirect, name='homeRedirect'),
    path('index/', views.homeRedirect, name='homeRedirect'),
    path('bank/', views.bank, name='bank'),
    path('editDrinks/', views.drinksEdit, name='editDrinks'),
    path('orderConfirmation/', views.orderConfirmation, name='orderConfirmation'),
    path('account/', views.account, name='account'),
    path('drinkMeister', views.drinkMeister, name='drinkMeister'),
    path('events', views.events, name='events'),
    path('manager', views.manager, name='manager'),
    path('verification', views.verification, name='verification'),
    path('createAccount', views.createAccount, name='createAccount'),
    path('addHoles', views.addHoles, name='addHoles'),

    # Django Auth
    path('login/', auth_views.LoginView.as_view(template_name="login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name="logout.html"), name='logout'),
]

src/main/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.utils import timezone
from django.db import models
import datetime


# Create your models here.

# NOTE: since we can't make variables private and still have Django work, we don't need to add getters and setters


class User(AbstractUser):
    USER_TYPE_CHOICES = (
        (1, 'Player'),
        (2, 'Sponsor'),
        (3, 'Drinkmeister'),
        (4, 'Manager'),
    )

    user_type = models.PositiveSmallIntegerField(default=1, choices=USER_TYPE_CHOICES)
    username = models.CharField(max_length=30, unique=True)
    password = models.CharField(max_length=300)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                                 message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True)  # validators should be a list
    email = models.EmailField(max_length=80)
    date_joined = models.DateTimeField(auto_now_add=True)  # This only evaluates when User instance is first made!
    balance = models.IntegerField(default=0)

    USERNAME_FIELD = 'username'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'email']

    def orderDrink(self, name, qty, instructions):
        for i in range(qty):
            order = Order()
            order.timeOrdered = models.TimeField(auto_now=True)
            order.drink = name
            order.specificInstructions = instructions
            order.served = False
            order.user = self
            order.save()


class Manager(models.Model):
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE, primary_key=True, related_name='manager')
    yearsWorked = models.IntegerField()
    mostMoneyHeld = models.IntegerField()
    drinksSold = models.IntegerField()
    totalTournamentsMade = models.IntegerField()
    communityPosts = models.TextField(max_length=2000, default="")

    @staticmethod
    def createTournament(name, startTime, endTime, sponsor, approved, completed):
        tournament = Tournament(name, startTime, endTime, sponsor, approved, completed)
        tournament.save()

    @staticmethod
    def editTournament(tournament, name, startTime, endTime, sponsor, approved, completed):
        tournament.name = name
        tournament.startTime = startTime
        tournament.endTime = endTime
        tournament.sponsor = sponsor
        tournament.approved = approved
        tournament.completed = completed
        tournament.save()

    @staticmethod
    def verifySponsor(sponsor):
        sponsor.canSponsorTournament = True
        sponsor.save()

    @staticmethod
    def verifyDrinkmeister(drinkmeister):
        drinkmeister.isAllowedToServeDrinks = True
        drinkmeister.save()

    @staticmethod
    def editDrink(drink, name, price, instructions):
        drink.name = name
        drink.price = price
        drink.instructions = instructions
        drink.save()

    @staticmethod
    def addDrink(name, price, instructions):
        drink = Drink(name, price, instructions)
        drink.save()


class Player(models.Model):
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE, primary_key=True, related_name='player')

    def joinTournament(self, tournament):
        tournament.players.add(self)
        tournament.save()
        for hole in tournament.holes.filter():
            newScore = Score(hole=hole, player=self, tournament=tournament)
            newScore.save()


class Sponsor(models.Model):
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE, primary_key=True, related_name='sponsor')
    companyName = models.CharField(max_length=300)
    canSponsorTournament = models.BooleanField(default=False)

    def sponsorTournament(self, tournament):
        if self.canSponsorTournament:
            tournament.sponsor.add(self)
            tournament.save()
        else:
            return "You do not have authorization to sponsor tournaments"


class Drinkmeister(models.Model):
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE, related_name='drinkmeister')
    employeeID = models.AutoField(primary_key=True)
    isAllowedToServeDrinks = models.BooleanField(default=False)

    def makeAndDeliverOrder(self, order):
        if self.isAllowedToServeDrinks:
            order.served = True
            order.save()
        else:
            return "You do not have authorization to serve drinks."

    def __str__(self):
        return str(self.user.first_name) + " " + str(self.employeeID)


class Drink(models.Model):
    name = models.CharField(max_length=300, primary_key=True)
    price = models.IntegerField()
    instructions = models.CharField(max_length=300)


class Order(models.Model):
    timeOrdered = models.TimeField(auto_now=True)
    drink = models.ForeignKey('Drink', on_delete=models.CASCADE)
    specificInstructions = models.CharField(max_length=300)
    served = models.BooleanField(default=False)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    location = models.IntegerField(default=0)


class TransactionManager(models.Manager):
    def create_transaction(self, amount, toAccount, fromAccount):
        transaction = self.create(amount=amount, account=toAccount, from_account=fromAccount)
        transaction.save()
        return transaction


class Transaction(models.Model):
    date = models.DateField(auto_now=True)
    from_account = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    amount = models.FloatField()
    account = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='user')
    objects = TransactionManager()


class Tournament(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=300, unique=True)
    date = models.DateField(unique=True)
    startTime = models.TimeField(default=datetime.time(9, 00))
    endTime = models.TimeField(default=datetime.time(14, 30))
    players = models.ManyToManyField('Player', blank=True)
    sponsor = models.ForeignKey('Sponsor', on_delete=models.CASCADE)
    approved = models.BooleanField(default=False)
    completed = models.BooleanField(default=False)
    holes = models.ManyToManyField('Hole')

    def addHoles(self, holeList):
        self.holes.add(holeList)
        self.save()

    def __str__(self):
        return str(self.name) + " tournament - " + str(self.date)


class Hole(models.Model):
    holeNumber = models.IntegerField(primary_key=True)
    par = models.SmallIntegerField(default=3)

    def __str__(self):
        return str(self.holeNumber)


class Score(models.Model):
    hole = models.ForeignKey('Hole', on_delete=models.CASCADE)
    tournament = models.ForeignKey('Tournament', on_delete=models.CASCADE)
    score = models.IntegerField(default=0)
    player = models.ForeignKey('Player', on_delete=models.CASCADE)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['hole', 'tournament', "player"], name="tournament_hole"),
        ]

    def __str__(self):
        return str(self.tournament) + ", " + str(self.hole) + ", " + str(self.player)


class Prize(models.Model):
    tournament = models.ForeignKey('Tournament', on_delete=models.CASCADE)
    amount = models.IntegerField()

src/main/forms.py
from django import forms
from django.forms import ModelForm
from .models import Drink


class addDrink(ModelForm):
    class Meta:
        model = Drink
        fields = "__all__"


class deleteDrink(forms.Form):
    drinkList = Drink.objects.all()
    drink = forms.ModelChoiceField(queryset=drinkList, required=False)


class editDrink(ModelForm):
    drinkList = Drink.objects.all()
    drink = forms.ModelChoiceField(queryset=drinkList, required=False)

    class Meta:
        model = Drink
        fields = ['drink', 'name', 'price', 'instructions']

src/main/templates/Bank.html
<!DOCTYPE html>

<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="description" content="Bank">
  <meta name="author" content="8th Wonder">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Bank</title>

</head>
<body>

{% include 'navBar.html' %}

<div class="Balance">

  <h2>Current Balance</h2>
  <p>$ 105.09</p>
  <a href="{% url 'transfer' %}"><input type="submit" value="Transfer">
  </a>

</div>


<div class="Recent Transfers">

  <h2>Recent Transfers</h2>

  <p>Drink -$10.00</p>
  <p>Incoming +$100.00</p>
  <p>Drink -$8.80</p>

</div>

</body>
</html>

src/main/templates/Sponsor Page.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />

    <title>Sponsor Tournament</title>

</head>
<body>
    <h1> 8th Wonder Putt Putt Golf</h1>
    <h1> Welcome to the Sponsor Page.</h1>

    {% include 'navBar.html' %}

    <div class="Sponsor New Tournament">

        <h2>Sponsor New Tournament</h2>

        <p>Check for available day.</p>
        <label for="date"></label><input type="datetime-local" name="date" id="date" value="">

        <label for="sponsor">Enter Sponsor Name: </label>
        <input id="sponsor" type="text" name="author" value="">

        <input type="submit" value="Sponsor Tournament - $500">


    </div>


    <div class="Current Tournaments">
        <h2>List of future tournaments here</h2>
    </div>


</body>
</html>

src/main/templates/account.html
<!DOCTYPE html>
<html >
<head>
    <meta charset="UTF-8">
    <meta name="description" content="Account Creation">
    <meta name="author" content="8th Wonder">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Account</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="stylesheet" media="screen and (max-width: 1040px)" href="{% static 'smallscreen.css' %}">
</head>

<body>

    {% include 'navBar.html' %}
    <h2 class="left column"> {{ user.username }}'s Profile</h2>
    <div class="left column">
        <h3>Account Information</h3>
        <h4>General Info</h4>
        <p><b>User Type:</b> {{ user.get_user_type_display }} <br>
            <b>Username:</b> {{ user.username }} <br>
            <b>Phone Number:</b> {{ user.phone_number }} <br>
            <b>Email:</b> {{ user.email }} <br>
            <b>Date Joined:</b> {{ user.date_joined }} <br>
            <b>Account Balance:</b> ${{ balance|floatformat:2 }} <br>
            {% if user.user_type == 4 %}
            <h4>Manager Info</h4>
                <b>Years worked:</b> {{ user.manager.yearsWorked }} <br>
                <b>Most Money Held:</b> {{ user.manager.mostMoneyHeld }} <br>
                <b>Drinks sold:</b> {{ user.manager.mostMoneyHeld }} <br>
                <b>Total Tournaments made:</b> {{ user.manager.totalTournamentsMade }} <br>
            {% endif %}
            {% if user.user_type == 3 %}
            <h4>Drinkmeister Employee Info</h4>
                <b>Employee ID:</b> {{ user.drinkmeister.employeeID }} <br>
            {% endif %}
            {% if user.user_type == 2 %}
            <h4>Sponsor Info</h4>
                <b>Company Name:</b> {{ user.sponsor.companyName }} <br>
            {% endif %}

        </p>

    </div>

    <div class="right column">
        <a href="{% url 'bank' %}">
        <button onclick="location.href='bank'" class="eventButton">
        <h2>Add Money to Account</h2>
        </button>
        </a>

        {% if user.user_type == 4 %}
        <h3>Other options</h3>
        {% include "manager.html" %}
    {% endif %}
    {% if user.user_type == 2 %}
        <h3>Other options</h3>
        {% include "sponsor.html" %}
    {% endif %}
        {% if user.user_type == 3 %}
        <h3>Other options</h3>
        <br>
    <a href="{% url 'drinkMeister' %}">
        <button onclick="location.href='drinkMeister'"  class="eventButton">
        <h2>Serve Drinks</h2>
        </button>
    </a>
    {% endif %}
    </div>


</body>
</html>

src/main/templates/addHoles.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="description" content="Bank Page">
    <meta name="author" content="8th Wonder">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bank Page</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="stylesheet" media="screen and (max-width: 1040px)" href="{% static 'smallscreen.css' %}">
</head>
<body>
    {% include 'navBar.html' %}

    <div class="column left">

        <form action="" method="post" id="addHole"> {% csrf_token %}
            Hole<br>
            <label for="hole">Hole Number: </label><input name="hole" id="hole" type="number"><br>
            <label for="par">Par: </label><input name="par" id="par" type="number" max="5"><br>
            <input type="submit" value="Submit" class="accountButton"> <button onclick="revealTransfer()" id="transfer-reveal">Cancel</button>
        </form>

    </div>

</body>

src/main/templates/drinkMeister.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="description" content="Main Page">
    <meta name="author" content="8th Wonder">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Orders</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="stylesheet" media="screen and (max-width: 1040px)" href="{% static 'smallscreen.css' %}">
</head>
<body>

{% include 'navBar.html' %}


<div class="left column" id="#orderNumber">

    <form class="right" style="width: 80%" action="{% url 'drinkMeister' %}" method="POST">{% csrf_token %}
        {% if orderList %}
            <select id="order" name="order" style="font-size: 1.5vw;">
            {% for order in orderList %}
                <option value="{{ order.id }}">{{ order.user }} - {{ order.drink.name }}</option>
            {% endfor %}
            </select>
                <a><input type="submit" value="Deliver and Finish Order" class="orderButton"></a>
            </form>
        {% endif %}

    <h1>Current Orders</h1>

    {% if orderList %}
    {% for order in orderList %}
    <div class="orderdiv">
        <p></p>
        <div id="{{ order.user }}" class="orderButton">Order From: {{ order.user }} </div>
        <div class="orderButton">Drink: {{ order.drink.name }}</div>
        <div class="orderButton">Instructions: {{ order.specificInstructions }}</div>
        <div class="orderButton">Time Ordered: {{ order.timeOrdered }}</div>
        <div class="orderButton">Deliver to Hole: {{ order.location }}</div>
    </div>


    {% endfor %}
    {% else %}
        <p></p>
        <h3>No Current Orders</h3>
    {% endif %}
</div>


    <div class="column right">
    <h2>Available Drinks</h2>
    {% if drinkList %}
    {% for drink in drinkList %}
      <div class="orderButton">
      <h3>{{ drink.name }}</h3>
      <p> - ${{ drink.price }}</p>
      <p> - {{ drink.instructions }}</p>
      </div>
    {% endfor %}
    {% else %}
      <p>No Drinks Yet Created</p>
    {% endif %}
    </div>

</body>
</html>

src/main/templates/events.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="description" content="Main Page">
    <meta name="author" content="8th Wonder">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Main Page</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="stylesheet" media="screen and (max-width: 1040px)" href="{% static 'smallscreen.css' %}">
</head>
<body>

{% include 'navBar.html' %}


<div class="column left">
    <h1 style="text-align:center;"> Upcoming Tournaments</h1>
{% if tournaments_list %}
<div>
    {% for t in tournaments_list %}
    <a href="{% url 'tournamentInfo' t.name %}">
        <button class="eventButton">
            <h2>{{t.name}}</h2>
            <h3>{{t.date}}: {{t.startTime}} to {{t.endTime}}</h3>
        </button>
    </a>
<br>
    {% endfor %}
</div>
{% else %}
<p>There are no upcoming tournaments</p>
{% endif %}
</div>


<div class="column right">
    <div class="communityPosts">
    <h2>Community Posts</h2><br>
        {% if user.user_type == 4 %}
            {% for m in manager_list %}
                {% if m == user.manager %}
                <form action="" method="post"> {% csrf_token %}
                    <textarea name="communityPosts" rows="7">{{m.communityPosts}}</textarea>
                    <input type="submit" value="Submit" class="eventButton">
                </form>
                {% endif %}
            {% endfor %}
        {% else%}
            {% for m in manager_list %}
                {{m.communityPosts}}
            {% endfor %}
        {% endif %}
    </div>
</div>

</body>
</html>

src/main/templates/index.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="description" content="Main Page">
    <meta name="author" content="8th Wonder">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Main Page</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="stylesheet" media="screen and (max-width: 1040px)" href="{% static 'smallscreen.css' %}">
</head>
<body>
    {% include 'navBar.html' %}

    <div class="column left">
        <div class="communityPosts">
            <h2>Community Posts</h2>
            {% if user.user_type == 4 %}
                {% for m in manager_list %}
                    <form action="" method="post"> {% csrf_token %}
                        <textarea name="communityPosts" rows="7">{{m.communityPosts}}</textarea>
                        <input type="submit" value="Submit" class="accountButton">
                    </form>
                {% endfor %}
            {% else%}
                {% for m in manager_list %}
                    {{m.communityPosts}}
                {% endfor %}
            {% endif %}

        </div>
    </div>



    <div class="column right">
        {% if top_score_list_last_tourney %}
            <h2>Top Scores from Latest Tournament</h2>
            {% for score in top_score_list_last_tourney %}
                <p>{{score.player.user.first_name}} {{score.player.user.last_name}}: {{score.score}}/{{score.tournament.numOfHoles}}</p>
            {% endfor %}
        {% else %}
            <h2>No Recent Tournaments</h2>
        {% endif %}

    </div>
</body>

src/main/templates/login.html
<!DOCTYPE html>
<html >
<head>
    <meta charset="UTF-8">
    <meta name="description" content="Login">
    <meta name="author" content="8th Wonder">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="stylesheet" media="screen and (max-width: 1040px)" href="{% static 'smallscreen.css' %}">
</head>

<body>

    {% include 'navBar.html' %}

<div class="left column">
    <h2>Please Sign in or Create Account</h2>
    <form method ="post">
        {% csrf_token %}
        {{ form.as_p }}

        <button type ="submit" class="accountButton">Login</button>
    </form>
    <p></p>

    <p></p>

    <a href="{% url 'accountCreation' %}"><input type="submit" value="Create New Account" class="accountButton"></a>

</div>


</body>
</html>

src/main/templates/logout.html
<!DOCTYPE html>
<html >
<head>
    <meta charset="UTF-8">
    <meta name="description" content="Account Creation">
    <meta name="author" content="8th Wonder">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Account</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="stylesheet" media="screen and (max-width: 1040px)" href="{% static 'smallscreen.css' %}">
</head>

<body>
{% include 'navBar.html' %}
<div class="left column">
    <div class="signoutDiv">Account successfully signed out </div>
</div>


</body>
</html>

src/main/templates/manager.html
<div class="managerOptions">

    <a href="{% url 'verification' %}">
        <button class="eventButton">
        <h2>Verify Users</h2>
        </button>
    </a>
<br>
    <a href="{% url 'events' %}">
        <button class="eventButton">
        <h2>Edit Tournaments</h2>
        </button>
    </a>
<br>
    <a href="{% url 'editDrinks' %}">
        <button onclick="location.href='drinks'" class="eventButton">
        <h2>Edit Drinks</h2>
        </button>
    </a>
    <a href="{% url 'addHoles' %}">
        <button class="eventButton">
        <h2>Add Holes</h2>
        </button>
    </a>
</div>

src/main/templates/orderConfirmation.html
<!DOCTYPE html>

<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="description" content="Order Confirmation">
  <meta name="author" content="8th Wonder">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Order Confirmation</title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'styles.css' %}">
  <link rel="stylesheet" media="screen and (max-width: 1040px)" href="{% static 'smallscreen.css' %}">
</head>
<body>

{% include 'navBar.html' %}



<div class="left column">

{% if success %}
  <h1>
    YAY!!!

    Your Order Has been Sent
  </h1>
{% elif not success %}
  <h1>
    Insufficient funds in your Account.

    Your Order Has NOT been Sent.
  </h1>

  <a href="{% url 'account' %}"><input type="submit" value="Check Account" class="accountButton"></a><br>

{% endif %}


  <a href="{% url 'drinks' %}"><input type="submit" value="New Order" class="accountButton"></a>

</div>

</body>
</html>

src/main/templates/sponsor.html
<!DOCTYPE html>

<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="description" content="Order Confirmation">
  <meta name="author" content="8th Wonder">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Sponsor</title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="stylesheet" media="screen and (max-width: 1040px)" href="{% static 'smallscreen.css' %}">
</head>
<body>



        <h2 style="margin-top: 0%;">Sponsor New Tournament</h2>
        <p>Check for available day.</p>
        <form action="" method="post"> {% csrf_token %}
            <label for="date"></label><input type="date" name="date" id="date" value="" class="eventButton" required>
            <br>
            <input id="tournamentName" name="tournamentName" type="text" placeholder="Enter Tournament Name" class="eventButton" required>
            <br>
            <input type="submit" value="Sponsor Tournament - $500" class="eventButton"/>
        </form>

    <p></p>
    <a href="{% url 'events' %}"><input type="submit" value="See Events" class="eventButton"></a>

src/main/templates/tournamentEdit.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="description" content="Tournament">
    <meta name="author" content="8th Wonder">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="stylesheet" media="screen and (max-width: 1040px)" href="{% static 'smallscreen.css' %}">
</head>

<body>

{% include 'navBar.html' %}

<div class="left column">
    <h2>Tournament: {{ tournament.name }}</h2>
    <form action="" method="post"> {% csrf_token %}
        {{tournament.startTime}}{{tournament.endTime}}{{tournament.date}}
        <label for="tournamentName">Tournament Name:</label><input type="text" name="tourneyName" id="tournamentName" value={{tournament.name}}/><br>
        <label for="startTime">Start:</label><input type="time" name="startTime" id="startTime" value={{tournament.startTime}}/><br>
        <label for="endTime">End:</label><input type="time" name="endTime" id="endTime" value={{tournament.endTime}}/><br>
        <label for="date">Date:</label><input type="date" name="date" id="date" value={{tournament.date}}/><br>

        <hr>
        <h2>Holes:</h2>
        {% for i in holes %}
            {% if i in tournamentHoles %}
            <label for="{{i}}">Hole {{i}}:</label><input type="checkbox" name="{{i}}" id="{{i}}" checked/><br>
            {% else %}
            <label for="{{i}}">Hole {{i}}:</label><input type="checkbox" name="{{i}}" id="{{i}}"/><br>
            {% endif %}
        {% endfor %}
        <input type="submit" name="submit" value="submit"/>
    </form>


</div>
<div class="right column">
    <h2>Players</h2>
    {% for player in tourney.players %}
    <p>Player {{player.first_name}} {{player.last_name}}</p>
    {% endfor %}
</div>

</body>
</html>

src/main/templates/tournamentInfo.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="description" content="Tournament">
    <meta name="author" content="8th Wonder">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="stylesheet" media="screen and (max-width: 1040px)" href="{% static 'smallscreen.css' %}">
</head>

<body>

{% include 'navBar.html' %}

<div class="left column">
    <h1>Tournament: {{ tournament.name }}</h1>
    <h2>{{tournament.date}}: {{tournament.startTime}} to {{tournament.endTime}}</h2>

    <p>Sponsor: {{ tournament.sponsor.user.first_name }} {{ tournament.sponsor.user.last_name }}</p>
    <p>Company: {{ tournament.sponsor.companyName }}</p>
    <p>Number of Holes: {{ numOfHoles }}</p>






</div>

    {% if user.user_type == 1 %}
    <div class="right column">
        <button onclick="location.href='play'" class="eventButton">
        <h2>Play</h2>
        </button>
    </div>
    {% endif %}
    {% if user.user_type == 4 or user.user_type == 2 and user.sponsor == tournament.sponsor %}
    <div class="right column">
        <button onclick="location.href='edit'" class="eventButton">
        <h2>Edit</h2>
        </button>
    </div>
    {% endif %}


</body>
</html>